name: 'CD - Deploy'

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: "index.docker.io"
  DOCKER_USERNAME: "mrgitau"
  LENDING_APP_API_IMAGE_NAME: "test-lending-svc"

jobs:
  ci-workflow:
    uses: tonygits/test-lending-svc/.github/workflows/ci-action.yaml@main
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    needs: [ci-workflow]

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build image
        run: docker build --tag $(echo $REGISTRY)/$(echo $DOCKER_USERNAME)/$(echo $LENDING_APP_API_IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Push image to Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $DOCKER_USERNAME)/$(echo $LENDING_APP_API_IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: [ 'build-and-push-docker-image' ]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: tonygits/lending-app-infra
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.email "gitau.ag@gmail.com"
          git config --global user.name "Anthony Gitau"
          echo ${{ github.sha }}
          sed -i "s#$(echo $DOCKER_USERNAME).*#$(echo $DOCKER_USERNAME)/$(echo $LENDING_APP_API_IMAGE_NAME):${{ github.sha }}#g" deployment.yaml
          git add -A
          git commit -am "Update image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin main
