# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 'CI Checks'

on:
  pull_request:
    branches:
      - 'main'

jobs:
  compile-and-test:
    name: Test
    runs-on: ubuntu-latest
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      #set up go version
      - name: Set up go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      #checkout repo
      - name: checkout repo
        uses: actions/checkout@v3

      #cache go modules
      - name: cache go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      #install static check
      - name: install static check
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.2.2

      #run static check
      - name: run static checks
        run: ~/go/bin/staticcheck ./...

      # build app
      - name: build lending app
        run: go build -o toprated main.go

      # run tests
      - name: Test
        run: go test -v -cover ./...


